name: Build Mod
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode-mod@main
        with:
          # Мы используем 'combine' (без D), как просит система в логах
          combine: true
          # Мы четко указываем цель
          target: Android
          
